BINARY =  dcdfecce-f5a0-554a-b96b-74a3e507fcff

TA_SIGN_KEY = ../mid_level_subkey.pem
TA_SUBKEY_BIN = ../mid_level_subkey.bin
TA_SUBKEY_ARGS = --subkey $(TA_SUBKEY_BIN) --name subkey1_ta
TA_SUBKEY_DEPS = $(TA_SUBKEY_BIN)

include ../ta_common.mk
