BINARY =  5c206987-16a3-59cc-ab0f-64b9cfc9e758

TA_SIGN_KEY = ../mid_level_subkey.pem
TA_SUBKEY_BIN = ../mid_level_subkey.bin
TA_SUBKEY_ARGS = --subkey $(TA_SUBKEY_BIN) --name subkey1_ta
TA_SUBKEY_DEPS = $(TA_SUBKEY_BIN)

include ../ta_common.mk
