// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2020, Microsoft Corporation
 */

#ifndef TA_OCALL_TEST_H
#define TA_OCALL_TEST_H

/* This UUID was generated with uuidgen */
#define TA_OCALL_UUID { 0x616906e4, 0x2fa8, 0x44c6, \
	{ 0xa6, 0x98, 0x2c, 0xf2, 0xd3, 0x5b, 0x99, 0xf9 } }

/* Command IDs understood by the TA */
#define TA_OCALL_CMD_NO_ECALL_PARAMS_NO_OCALL_PARAMS                       0
#define TA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_VALUE_PARAMS                    1
#define TA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_MEMREF_PARAMS                   2
#define TA_OCALL_CMD_NULL_MEMREF_PARAMS                                    3
#define TA_OCALL_CMD_NULL_MEMREF_PARAMS_MIXED                              4
#define TA_OCALL_CMD_NULL_MEMREF_PARAMS_INVALID                            5
#define TA_OCALL_CMD_PREMATURE_SESSION_CLOSE                               6
#define TA_OCALL_CMD_GET_PREMATURE_SESSION_CLOSE_STATUS                    7
#define TA_OCALL_CMD_PREMATURE_CONTEXT_FINALIZE                            8
#define TA_OCALL_CMD_GET_PREMATURE_CONTEXT_FINALIZE_STATUS                 9
#define TA_OCALL_CMD_OPEN_SESSION_OCALL                                    10
#define TA_OCALL_CMD_OPEN_SESSION_OCALL_PREMATURE_CONTEXT_FINALIZE         11
#define TA_OCALL_CMD_OPEN_SESSION_OCALL_PREMATURE_CONTEXT_FINALIZE_STATUS  12

/* Command IDs understood by the CA */
#define CA_OCALL_CMD_NO_ECALL_PARAMS_NO_OCALL_PARAMS \
	TA_OCALL_CMD_NO_ECALL_PARAMS_NO_OCALL_PARAMS
#define CA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_VALUE_PARAMS \
	TA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_VALUE_PARAMS
#define CA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_MEMREF_PARAMS \
	TA_OCALL_CMD_NO_ECALL_PARAMS_OCALL_MEMREF_PARAMS
#define CA_OCALL_CMD_NULL_MEMREF_PARAMS \
	TA_OCALL_CMD_NULL_MEMREF_PARAMS
#define CA_OCALL_CMD_NULL_MEMREF_PARAMS_MIXED \
	TA_OCALL_CMD_NULL_MEMREF_PARAMS_MIXED
#define CA_OCALL_CMD_NULL_MEMREF_PARAMS_INVALID \
	TA_OCALL_CMD_NULL_MEMREF_PARAMS_INVALID
#define CA_OCALL_CMD_PREMATURE_SESSION_CLOSE \
	TA_OCALL_CMD_PREMATURE_SESSION_CLOSE
#define CA_OCALL_CMD_PREMATURE_CONTEXT_FINALIZE \
	TA_OCALL_CMD_PREMATURE_CONTEXT_FINALIZE
#define CA_OCALL_CMD_OPEN_SESSION_OCALL \
	TA_OCALL_CMD_OPEN_SESSION_OCALL
#define CA_OCALL_CMD_OPEN_SESSION_OCALL_PREMATURE_CONTEXT_FINALIZE \
	TA_OCALL_CMD_OPEN_SESSION_OCALL_PREMATURE_CONTEXT_FINALIZE

#endif /* TA_OCALL_TEST_H */
