BINARY =  a720ccbb-51da-417d-b82e-e5445d474a7a

TA_SIGN_KEY = ../identity_subkey2.pem
TA_SUBKEY_BIN = ../identity_subkey2.bin
TA_SUBKEY_ARGS = --subkey $(TA_SUBKEY_BIN)
TA_SUBKEY_DEPS = $(TA_SUBKEY_BIN)

include ../ta_common.mk
